# - name: installing nginx
#   hosts: node1
#   become: yes
#   tasks:
#   - name: Install nginx
#     ansible.builtin.yum:
#       name: nginx
#       state: installed
#   - name: starting nginx
#     ansible.builtin.service:
#       name: nginx
#       state: started

- name: installing nginx
  hosts: node1
  become: yes
  tasks:
    - name: installing nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name : starting nginx
      ansible.builtin.service:
        name: nginx
        state: started