- name: installing redis component
  hosts: redis
  become: yes
  tasks: 
    - name: installing redis repo
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: installed
        disable_gpg_check: true

    - name: enable redis
      command: yum module enable redis:remi-6.2 -y